plugins:
  - rubocop-rails
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'log/**/*'
    - 'test/**/*'
    - 'spec/**/*'
    - 'Gemfile'
    - 'Rakefile'

# Disable style-only rules that don't affect functionality
Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/TrailingWhitespace:
  Enabled: true

Bundler/OrderedGems:
  Enabled: false  # Not critical for functionality

# Disable non-critical Rails rules
Rails/I18nLocaleTexts:
  Enabled: false  # Not critical for preventing bad code

Rails/HttpStatusNameConsistency:
  Enabled: false  # Warning only, not critical

Rails/StrongParametersExpect:
  Enabled: false  # Test-related, not critical

Rails/ApplicationRecord:
  Enabled: false  # Legacy models are fine

Rails/RakeEnvironment:
  Enabled: false  # Not critical

Style/RedundantConstantBase:
  Enabled: false

Style/ExpandPathArguments:
  Enabled: false

Layout/LineLength:
  Max: 200  # Increased limit to avoid false positives

Style/SoleNestedConditional:
  Enabled: false  # Not critical for preventing bad code

# Performance Rules - Critical for preventing bad queries
Performance:
  Enabled: true
  Exclude:
    - 'db/**/*'
    - 'config/**/*'

Performance/Count:
  Enabled: true

Performance/Detect:
  Enabled: true

Performance/StartWith:
  Enabled: true

Performance/EndWith:
  Enabled: true

Performance/RegexpMatch:
  Enabled: true

# Rails-specific rules
Rails:
  Enabled: true

Rails/FindEach:
  Enabled: true
  Description: 'Use find_each instead of each to avoid loading all records into memory'

Rails/FindBy:
  Enabled: true

Rails/InverseOf:
  Enabled: true

Rails/HasManyOrHasOneDependent:
  Enabled: true

Rails/IndexBy:
  Enabled: true

Rails/IndexWith:
  Enabled: true

Rails/Pluck:
  Enabled: true
  Description: 'Use pluck instead of map when you only need specific attributes'

Rails/SkipsModelValidations:
  Enabled: true

# Custom rules for query optimization
Style/HashSyntax:
  Enabled: true

Style/StringLiterals:
  Enabled: false  # Allow both single and double quotes

# Prevent common bad practices
Style/GuardClause:
  Enabled: true

Style/IfUnlessModifier:
  Enabled: true

Metrics/AbcSize:
  Max: 20
  Exclude:
    - 'db/migrate/**/*'

Metrics/BlockLength:
  Max: 100
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'config/**/*'
    - 'lib/tasks/**/*'

Metrics/ClassLength:
  Max: 200

Metrics/MethodLength:
  Max: 30
  Exclude:
    - 'db/migrate/**/*'

Metrics/ModuleLength:
  Max: 200

Metrics/ParameterLists:
  Max: 5

# Note: Rails/Unscoped cop doesn't exist in rubocop-rails
# Use custom query checks via rake task instead
